print()
name = str(input("What is your name?\n "))
print()
print("Welcome!\n",name)
print()
bill = int(input("What is your amount? \n").strip('$'))
percentage = float(input("Enter the percentage of tip ammount that you want to pay\n").strip('%'))
print()
print("...........................................................")
print()
tip = (int(bill)  / 100) * int(percentage)
#percent = bill*(100/total)
print(f"Your Tip is {tip}")
print()
print("Thankyou for providing infromation.")
print("...........................................................")